In [1]:
import sys
import torch
import visdom
import argparse
import numpy as np
import torch.nn as nn
import scipy.misc as misc
import torch.nn.functional as F
import torchvision.models as models

from torch.autograd import Variable
from torch.utils import data
from tqdm import tqdm

from ptsemseg.loader import get_loader, get_data_path
from ptsemseg.metrics import scores

from glob import glob
import os

# Predict

In [2]:
def predict(img_path, dataset, model_path, out_path):

    # Setup image
    print("Read Input Image from : {}".format(img_path))
    img = misc.imread(img_path)

    data_loader = get_loader(dataset)
    data_path = get_data_path(dataset)
    loader = data_loader(data_path, is_transform=True)
    n_classes = loader.n_classes

    img = img[:, :, ::-1]
    img = img.astype(np.float64)
    img -= loader.mean
#     img = misc.imresize(img, (loader.img_size[0], loader.img_size[1]))
    img = img.astype(float) / 255.0
    # NHWC -> NCWH
    img = img.transpose(2, 0, 1) 
    img = np.expand_dims(img, 0)
    img = torch.from_numpy(img).float()

    # Setup Model
    model = torch.load(model_path)
    model.eval()

    if torch.cuda.is_available():
        model.cuda(0)
        images = Variable(img.cuda(0))
    else:
        images = Variable(img)

    outputs = model(images)
    pred = np.squeeze(outputs.data.max(1)[1].cpu().numpy(), axis=0)
#     decoded = loader.decode_segmap(pred)
    print(np.unique(pred))
#     misc.imsave(out_path, decoded)
    misc.toimage(pred, cmin=0, cmax=255).save(out_path)
    print("Segmentation Mask Saved at: {}".format(out_path))

In [3]:
dataset = 'pascal'
model_path = '/home/dongwonshin/Desktop/pytorch-semseg/weights/fcn16s_pascal_1_99.pkl'
output_path = '/home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99'

with open('/home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/val.txt') as fp:
    contents = fp.readlines()

for n, content in enumerate(contents):
    img_path = (os.path.join('/home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img',content[:-1]+'.jpg'))
    out_path = os.path.join(output_path,content[:-1]+'.png')
    
#     print(img_path)
#     print(out_path)
    
    predict(img_path, dataset, model_path, out_path)

Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_000003.jpg


/home/dongwonshin/.local/lib/python3.5/site-packages/torch/serialization.py:316: SourceChangeWarning: source code of class 'torch.nn.modules.container.Sequential' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/dongwonshin/.local/lib/python3.5/site-packages/torch/serialization.py:316: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/dongwonshin/.local/lib/python3.5/site-packages/torch/nn/functional.py:1423: UserWarning: nn.functional.upsample_bilinear is deprecated. Use nn.functional.upsample instead.
  warnings.warn("nn.functional.upsample_bil

[ 0  4  6 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_000003.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_000007.jpg
[0 4 5 6]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_000007.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_000009.jpg
[ 0 10 12]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_000009.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_000027.jpg
[ 0  7 14 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_000027.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_000043.jpg
[ 0  8  9 11]
Segmentation Mask Saved at: /home/don

[ 0  4 18 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_000281.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_000305.jpg
[ 0  9 11 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_000305.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_000307.jpg
[ 0  2 15 16]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_000307.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_000321.jpg
[ 0  9 11 18 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_000321.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_000339.jpg
[ 0  3 14 18 19]
Segmentation Mask Saved 

[0 8]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_000581.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_000589.jpg
[ 0  7  9 18 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_000589.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_000599.jpg
[ 0  5  7  9 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_000599.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_000605.jpg
[ 0 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_000605.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_000609.jpg
[ 0  1  2  3  4 14 15]
Segmentation Mask Saved at

[0 8]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_000839.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_000853.jpg
[0 2 5]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_000853.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_000857.jpg
[ 0 13 16 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_000857.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_000863.jpg
[ 0 12 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_000863.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_000885.jpg
[ 0  5  9 11 15 18]
Segmentation Mask Saved at: /home/dongwon

[ 0  3 13]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_001185.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_001199.jpg
[ 0  5 14 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_001199.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_001205.jpg
[ 0  5 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_001205.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_001221.jpg
[ 0  4  5 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_001221.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_001225.jpg
[ 0  2  8 15]
Segmentation Mask Saved at:

[ 0  4  9 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_001503.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_001513.jpg
[ 0  7  8 12 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_001513.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_001527.jpg
[ 0 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_001527.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_001531.jpg
[ 0  2 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_001531.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_001539.jpg
[ 0  9 11 13 15]
Segmentation Mask Saved 

[ 0 15 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_001765.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_001769.jpg
[ 0  9 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_001769.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_001773.jpg
[ 0  9 11 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_001773.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_001805.jpg
[ 0  1 15 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_001805.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_001815.jpg
[ 0 20]
Segmentation Mask Saved at: /home/do

[ 0  3  8 13 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_002013.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_002017.jpg
[ 0 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_002017.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_002021.jpg
[ 0 15 16]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_002021.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_002031.jpg
[ 0 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_002031.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_002035.jpg
[ 0 14 15 18 19]
Segmentation Mask Saved at: /home/dongw

[ 0  5  7  8 10 12 18 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_002267.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_002269.jpg
[ 0  2  9 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_002269.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_002273.jpg
[ 0  1  5 11 14 15 16]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_002273.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_002283.jpg
[ 0 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_002283.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_002293.jpg
[ 0  3  8 11 12 15 17]
Segmen

[ 0  3  8 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_002597.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_002599.jpg
[ 0  8 10 11 12 13 14 15 17 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_002599.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_002603.jpg
[ 0  3  8 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_002603.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_002623.jpg
[ 0  8 15 18 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_002623.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_002631.jpg
[ 0  2  6  7 14 15 19]


[0 3]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_002847.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_002859.jpg
[ 0  8 12 15 16 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_002859.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_002869.jpg
[ 0  9 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_002869.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_002875.jpg
[ 0  7 14]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_002875.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_002879.jpg
[ 0  6 15]
Segmentation Mask Saved at: /home/dong

[ 0  8 12 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_003181.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_003187.jpg
[ 0  4 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_003187.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_003189.jpg
[ 0  1  4  7 11 18 19 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_003189.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_003193.jpg
[ 0  2  4  5 11 14 15 16 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_003193.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_003205.jpg
[ 0  2  7 15]
Segmen

[ 0 13 15 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_003461.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_003467.jpg
[ 0  5 11 15 18 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_003467.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_003475.jpg
[0 1 4 7]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_003475.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_003477.jpg
[ 0  2  9 11 16 18 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_003477.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_003479.jpg
[ 0  7 14 15]
Segmentation Mask S

[ 0  7 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_003755.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_003763.jpg
[ 0  3  8 10 12 17 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_003763.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_003767.jpg
[ 0  1 13 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_003767.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_003775.jpg
[ 0 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_003775.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_003777.jpg
[ 0  1  6  7 19]
Segmentation Mask Saved at:

[ 0  8 12 17]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_004007.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_004015.jpg
[ 0  3 10 12 16]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_004015.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_004027.jpg
[ 0 16]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_004027.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_004045.jpg
[ 0  3 13 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_004045.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_004069.jpg
[0 7]
Segmentation Mask Saved at: /home/dong

[ 0  1  4  7  9 11 18 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_004289.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_004297.jpg
[ 0  8  9 12 15 18 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_004297.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_004317.jpg
[ 0  3  8 10 12 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_004317.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_004327.jpg
[ 0  2 15 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_004327.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_004333.jpg
[ 0  1  4  5 15 2

[ 0 14 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_004549.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_004553.jpg
[ 0  9 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_004553.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_004575.jpg
[ 0  9 11 15 16]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_004575.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_004579.jpg
[0 8 9]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_004579.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_004589.jpg
[ 0 16]
Segmentation Mask Saved at: /home/dongwons

[ 0  4  9 15 18 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_004881.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_004885.jpg
[ 0  1 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_004885.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_004887.jpg
[ 0  1  7  9 11 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_004887.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_004907.jpg
[0 4]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_004907.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_004921.jpg
[0 4]
Segmentation Mask Saved at: /home/don

[ 0  7  9 14 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_005151.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_005167.jpg
[ 0  9 12 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_005167.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_005181.jpg
[ 0 12 13 15 17]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_005181.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_005185.jpg
[ 0 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_005185.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_005191.jpg
[ 0  9 19 20]
Segmentation Mask Saved at:

[ 0  7  8 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_005421.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_005423.jpg
[ 0 14 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_005423.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_005427.jpg
[ 0  1  7 14 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_005427.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_005431.jpg
[ 0 15 16]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_005431.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_005439.jpg
[ 0  5  9 15 19 20]
Segmentation Mask Saved at:

[0 8]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_005699.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_005701.jpg
[ 0  5  9 11 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_005701.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_005703.jpg
[ 0  2 12 16 17 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_005703.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_005721.jpg
[0 4 7]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_005721.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_005727.jpg
[ 0  2 15]
Segmentation Mask Saved at: /home/dong

[ 0  3  8 12 13 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_006007.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_006017.jpg
[ 0  7 14]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_006017.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_006021.jpg
[ 0  4 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_006021.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_006027.jpg
[ 0  5 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_006027.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_006031.jpg
[ 0  7 11 20]
Segmentation Mask Saved at: /home

[0 1]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_006269.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_006275.jpg
[ 0  2  4  7 15 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_006275.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_006285.jpg
[0 8]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_006285.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_006303.jpg
[ 0  9 16 18 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_006303.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_006307.jpg
[ 0  8 12 15]
Segmentation Mask Saved at: /home/don

[ 0  5 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_006605.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_006609.jpg
[ 0  8 12 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_006609.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_006611.jpg
[ 0  2  9 15 16 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_006611.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_006617.jpg
[ 0 15 18 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_006617.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_006621.jpg
[0 1]
Segmentation Mask Saved at: /home/d

[0 7]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_006885.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_006907.jpg
[0 7]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_006907.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_006925.jpg
[0 4]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_006925.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_006939.jpg
[ 0  8 13 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_006939.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_006941.jpg
[ 0  3  5  9 14 15 18]
Segmentation Mask Saved at: /home/dongwonshin

[ 0 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_007189.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_007195.jpg
[ 0  1  7 13 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_007195.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_007207.jpg
[ 0  9 11 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_007207.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_007219.jpg
[ 0  5 11 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_007219.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_007225.jpg
[ 0  9 15 16]
Segmentation Mask Saved at: /h

[ 0  8 12 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_007455.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_007459.jpg
[ 0  2  7 14 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_007459.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_007461.jpg
[ 0  8 12 13 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_007461.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_007497.jpg
[ 0  2 10 13 15 17 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_007497.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_007501.jpg
[ 0  3  5 16]
Segmentation Ma

[ 0  8 12 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_007735.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_007737.jpg
[ 0  5  7 15 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_007737.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_007739.jpg
[ 0  7 14]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_007739.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_007741.jpg
[ 0  1  9 15 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_007741.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_007745.jpg
[ 0  9 13 15]
Segmentation Mask Saved 

[ 0  2  3  4 14 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_007993.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_008001.jpg
[ 0  7 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_008001.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_008011.jpg
[ 0 13]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_008011.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_008025.jpg
[0 1]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_008025.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_008029.jpg
[ 0 15 18]
Segmentation Mask Saved at: /home/dongwonshi

[ 0  9 15 18 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_008271.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_008279.jpg
[ 0  3  5  8  9 13 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_008279.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_008297.jpg
[ 0 14 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_008297.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_008301.jpg
[ 0  6 15 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_008301.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_008307.jpg
[ 0  1  2  7 14 15]
Segmentation Ma

[ 0  8 12 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_008585.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_008595.jpg
[ 0  3 15 16]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_008595.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_008611.jpg
[0 2]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_008611.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_008613.jpg
[ 0 10 13 17]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2008_008613.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2008_008615.jpg
[ 0 15 19]
Segmentation Mask Saved at: /home/dong

[ 0  8 12 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_000063.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_000067.jpg
[ 0  1 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_000067.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_000087.jpg
[ 0  9 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_000087.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_000089.jpg
[0 6 7]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_000089.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_000093.jpg
[ 0  4  9 16]
Segmentation Mask Saved at: /home/do

[ 0  1  7 14 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_000397.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_000399.jpg
[0 7]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_000399.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_000411.jpg
[ 0  1  2  7 14 15 18 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_000411.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_000417.jpg
[0 1]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_000417.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_000421.jpg
[ 0  4 15]
Segmentation Mask Saved at: /home/

[ 0  1  3  4  7 12 15 17]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_000661.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_000675.jpg
[ 0  3 17]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_000675.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_000677.jpg
[ 0  3  8 12 13]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_000677.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_000681.jpg
[0 3 8]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_000681.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_000683.jpg
[ 0  1  7  8 14]
Segmentation Mask Sav

[ 0  1 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_000909.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_000919.jpg
[0 4]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_000919.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_000923.jpg
[ 0 12 15 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_000923.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_000925.jpg
[ 0  7  9 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_000925.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_000931.jpg
[ 0 13]
Segmentation Mask Saved at: /home/dongwonshin/D

[ 0  9 16 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_001249.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_001255.jpg
[ 0  2  7 14 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_001255.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_001257.jpg
[ 0 10 13]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_001257.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_001259.jpg
[ 0  4 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_001259.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_001279.jpg
[0 8]
Segmentation Mask Saved at: /home/dongwon

[ 0  1 14 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_001479.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_001501.jpg
[0 1]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_001501.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_001505.jpg
[ 0 17]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_001505.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_001509.jpg
[ 0  1  4  7 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_001509.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_001519.jpg
[ 0  1  4  6  7  9 15 19]
Segmentation Mask Saved at: /

[ 0  4 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_001709.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_001713.jpg
[0 1]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_001713.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_001723.jpg
[0 4]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_001723.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_001731.jpg
[ 0 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_001731.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_001733.jpg
[ 0  8 12 16]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/p

[ 0 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_001977.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_001979.jpg
[ 0 12 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_001979.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_001991.jpg
[ 0  3 12 17]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_001991.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_001997.jpg
[0 1 4]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_001997.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_002001.jpg
[0 4]
Segmentation Mask Saved at: /home/dongwonshin/Desktop

[ 0  4 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_002219.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_002221.jpg
[ 0  3  8 10 12 13]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_002221.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_002231.jpg
[ 0 10 13]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_002231.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_002239.jpg
[ 0  1  5  7  8 14 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_002239.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_002257.jpg
[ 0  2 13 14 15]
Segmentation Mask 

[ 0 13 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_002515.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_002517.jpg
[0 6 7]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_002517.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_002521.jpg
[0 4 5]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_002521.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_002525.jpg
[0 2 3 8]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_002525.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_002527.jpg
[ 0  3  8 12 16]
Segmentation Mask Saved at: /home/dongwonshin/

[ 0  3 14 16]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_002741.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_002743.jpg
[ 0  5  9 11 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_002743.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_002749.jpg
[0 5]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_002749.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_002753.jpg
[0 3 8]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_002753.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_002755.jpg
[ 0  9 16 18 19 20]
Segmentation Mask Saved at: /home/d

[ 0  2  8 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_003065.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_003071.jpg
[ 0  9 11 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_003071.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_003083.jpg
[ 0  2  4 13 14 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_003083.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_003089.jpg
[ 0  3 10 17]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_003089.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_003097.jpg
[ 0  1 19]
Segmentation Mask Saved 

[ 0  5 15 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_003347.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_003351.jpg
[ 0  1  4  6  7 15 16 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_003351.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_003373.jpg
[ 0  9 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_003373.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_003375.jpg
[ 0  3  8 12 13]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_003375.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_003379.jpg
[ 0 15]
Segmentation Mask Saved 

[0 1]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_003571.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_003581.jpg
[ 0  5  9 15 18 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_003581.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_003589.jpg
[0 6 7]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_003589.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_003607.jpg
[ 0  8  9 12 13 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_003607.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_003627.jpg
[ 0  1  3  5  8 12 15]
Segmentation Mask Sa

[ 0  3 13]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_003903.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_003905.jpg
[ 0  2  7 13 14 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_003905.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_003911.jpg
[0 3 8]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_003911.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_003929.jpg
[ 0 14 15 16]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_003929.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_003947.jpg
[0 1]
Segmentation Mask Saved at: /home/dongwon

[ 0  8 12]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_004193.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_004197.jpg
[ 0  6 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_004197.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_004203.jpg
[0 1]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_004203.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_004205.jpg
[ 0 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_004205.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_004207.jpg
[ 0  1  2 14]
Segmentation Mask Saved at: /home/dongwonshin/Desk

[0 8]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_004509.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_004525.jpg
[ 0  3 15 18 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_004525.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_004529.jpg
[0 8]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_004529.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_004535.jpg
[0 1]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_004535.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_004537.jpg
[ 0  1  9 11 16 18]
Segmentation Mask Saved at: /home/dongwonshin

[ 0 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_004799.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_004801.jpg
[ 0  4 14 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_004801.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_004823.jpg
[ 0  9 15 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_004823.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_004841.jpg
[ 0  8 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_004841.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_004845.jpg
[ 0 14]
Segmentation Mask Saved at: /home/dongwons

[ 0 17 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_005089.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_005103.jpg
[ 0  1  2  9 14 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_005103.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_005111.jpg
[0 1]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_005111.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_005119.jpg
[0 3 8]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2009_005119.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2009_005137.jpg
[ 0  3 16]
Segmentation Mask Saved at: /home/dongwonshi

[ 0  7 15 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_000053.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_000065.jpg
[ 0  3  5  8 16 17]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_000065.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_000069.jpg
[ 0  6  7 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_000069.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_000083.jpg
[ 0  2 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_000083.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_000085.jpg
[ 0  6 19]
Segmentation Mask Saved at: /h

[0 3]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_000335.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_000375.jpg
[ 0  4  7  9 11 14 15 18 19 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_000375.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_000379.jpg
[ 0  4  5  7 19 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_000379.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_000381.jpg
[0 7]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_000381.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_000399.jpg
[ 0  2  4 19]
Segmentation Mask Save

[ 0  4 11 15 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_000669.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_000679.jpg
[ 0  4 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_000679.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_000683.jpg
[ 0  8 17]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_000683.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_000689.jpg
[ 0  7 14 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_000689.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_000695.jpg
[ 0  7 14 15]
Segmentation Mask Saved at: /home

[ 0 14]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_000929.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_000931.jpg
[ 0 15 19 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_000931.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_000941.jpg
[ 0  3  8 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_000941.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_000945.jpg
[ 0  4  6  7 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_000945.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_000947.jpg
[0 6 7]
Segmentation Mask Saved at: /home/do

[ 0 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_001151.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_001163.jpg
[0 4 7]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_001163.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_001181.jpg
[ 0  9 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_001181.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_001189.jpg
[ 0  1 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_001189.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_001201.jpg
[ 0  3 17]
Segmentation Mask Saved at: /home/dongwonshin/De

[ 0  3  8 17]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_001441.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_001449.jpg
[ 0  7 15 16]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_001449.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_001451.jpg
[ 0  8 10 12 17]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_001451.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_001453.jpg
[ 0  6  7 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_001453.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_001455.jpg
[ 0  5  9 14]
Segmentation Mask Saved at:

[0 7]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_001685.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_001697.jpg
[0 3]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_001697.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_001699.jpg
[ 0 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_001699.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_001705.jpg
[ 0  3 12]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_001705.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_001717.jpg
[ 0 16]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pyto

[ 0  2  8 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_001921.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_001927.jpg
[0 1 3]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_001927.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_001929.jpg
[ 0  7  8  9 12 13 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_001929.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_001937.jpg
[ 0  3  8 10 12 13 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_001937.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_001951.jpg
[ 0 15 19]
Segmentation Mask 

[ 0 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_002223.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_002229.jpg
[0 1 4]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_002229.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_002245.jpg
[ 0 15 19 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_002245.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_002247.jpg
[ 0 13 15 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_002247.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_002251.jpg
[ 0 14 15]
Segmentation Mask Saved at: /home/dongwonshin

[0 8]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_002543.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_002547.jpg
[ 0 17]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_002547.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_002561.jpg
[ 0 11 12 15 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_002561.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_002565.jpg
[0 4]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_002565.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_002569.jpg
[ 0  3 17]
Segmentation Mask Saved at: /home/dongwonshin/Deskto

[ 0  8  9 12 13 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_002789.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_002791.jpg
[ 0  1  7 15 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_002791.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_002793.jpg
[ 0  3  4  7 12 15 18 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_002793.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_002803.jpg
[0 3 4]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_002803.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_002807.jpg
[ 0  7 12 15]
Segmentation Ma

[ 0  7 16]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_003123.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_003127.jpg
[0 1 7]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_003127.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_003129.jpg
[ 0  6  7 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_003129.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_003133.jpg
[0 8]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_003133.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_003135.jpg
[ 0 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desk

[0 1]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_003365.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_003375.jpg
[ 0 12 13 15 17]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_003375.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_003379.jpg
[ 0  2 14]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_003379.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_003381.jpg
[ 0  7 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_003381.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_003385.jpg
[ 0  7 15 20]
Segmentation Mask Saved at: /home/dongwon

[ 0  5  9 11 15 16 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_003597.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_003603.jpg
[ 0  2 14 15 16]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_003603.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_003605.jpg
[ 0  2 14]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_003605.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_003609.jpg
[ 0 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_003609.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_003613.jpg
[ 0 15 18]
Segmentation Mask Saved at: /h

[ 0 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_003847.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_003855.jpg
[ 0  4  6  7 15 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_003855.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_003857.jpg
[ 0  7 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_003857.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_003859.jpg
[ 0  3 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_003859.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_003861.jpg
[ 0 15 18]
Segmentation Mask Saved at: /home/dongw

[ 0  8 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_004141.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_004143.jpg
[ 0  1  7 14]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_004143.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_004145.jpg
[ 0 13]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_004145.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_004149.jpg
[ 0 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_004149.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_004157.jpg
[0 8]
Segmentation Mask Saved at: /home/dongwonshin/Desk

[ 0  7 11 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_004391.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_004409.jpg
[ 0  9 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_004409.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_004415.jpg
[ 0  7  8  9 16 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_004415.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_004417.jpg
[ 0  1  2  3  5  8  9 12 17 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_004417.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_004419.jpg
[0 1]
Segmentation M

[ 0  6  7 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_004637.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_004659.jpg
[ 0 17]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_004659.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_004661.jpg
[ 0  2  4  6  7 15 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_004661.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_004667.jpg
[ 0  3  8 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_004667.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_004677.jpg
[ 0 19]
Segmentation Mask Saved at: /h

[ 0  8 13 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_004891.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_004901.jpg
[ 0 12 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_004901.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_004903.jpg
[ 0  6  7 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_004903.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_004909.jpg
[ 0 18 19 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_004909.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_004913.jpg
[0 3 8]
Segmentation Mask Saved at: /home/do

[ 0  5  8 12 13 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_005159.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_005167.jpg
[ 0  1  2  4  7 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_005167.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_005169.jpg
[ 0  8 12 16 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_005169.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_005185.jpg
[0 8]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_005185.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_005187.jpg
[ 0  4 16]
Segmentation Mask Saved at

[0 3]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_005531.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_005543.jpg
[ 0  5 11 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_005543.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_005551.jpg
[ 0  8 12]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_005551.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_005567.jpg
[ 0  3  9 17]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_005567.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_005575.jpg
[ 0  5  8  9 11 12 18 20]
Segmentation Mask Saved at: /

[0 1]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_005877.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_005883.jpg
[ 0  5  7  9 15 18 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_005883.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_005885.jpg
[ 0  8 12]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_005885.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_005897.jpg
[ 0 12 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2010_005897.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2010_005899.jpg
[0 8]
Segmentation Mask Saved at: /home/dongwonsh

[ 0 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_000061.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_000065.jpg
[ 0  9 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_000065.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_000071.jpg
[ 0  3  5  8 15 16 18 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_000071.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_000077.jpg
[ 0  4 19 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_000077.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_000083.jpg
[ 0  8 12 15 18]
Segmentation Mask Saved 

[ 0 14 15 18 19 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_000445.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_000455.jpg
[ 0 14 15 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_000455.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_000471.jpg
[ 0 13 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_000471.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_000477.jpg
[ 0  8 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_000477.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_000479.jpg
[ 0 15]
Segmentation Mask Saved at: /home

[ 0  8 12 13 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_000789.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_000807.jpg
[0 1 8]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_000807.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_000809.jpg
[ 0  3  9 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_000809.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_000813.jpg
[ 0  8  9 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_000813.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_000843.jpg
[ 0  5  9 15 16]
Segmentation Mask Saved at:

[ 0  4  5 14 15 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_001161.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_001167.jpg
[ 0  9 11 16 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_001167.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_001190.jpg
[0 4 6 8]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_001190.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_001201.jpg
[ 0 12 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_001201.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_001203.jpg
[ 0 14 15 16]
Segmentation Mask Saved a

[ 0  2  3  4  8 14]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_001421.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_001441.jpg
[ 0  2  7  8 14]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_001441.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_001447.jpg
[ 0  9 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_001447.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_001467.jpg
[ 0  7 15 18 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_001467.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_001471.jpg
[0 3]
Segmentation Mask Saved at: /

[ 0 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_001741.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_001745.jpg
[ 0  8 12]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_001745.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_001747.jpg
[ 0  6  7 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_001747.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_001751.jpg
[ 0  1  9 13 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_001751.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_001757.jpg
[ 0 17]
Segmentation Mask Saved at: /home/dongwons

[ 0 10 13 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_002047.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_002075.jpg
[ 0  7 11 13 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_002075.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_002079.jpg
[ 0  6 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_002079.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_002091.jpg
[0 1]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_002091.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_002093.jpg
[ 0 14 15]
Segmentation Mask Saved at: /home/dong

[ 0  8 15 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_002409.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_002429.jpg
[ 0  8  9 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_002429.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_002459.jpg
[ 0  3  4  7 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_002459.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_002463.jpg
[0 3 5 8]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_002463.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_002479.jpg
[ 0 14 15]
Segmentation Mask Saved at: /home/

[ 0  9 11 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_002805.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_002817.jpg
[ 0 17]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_002817.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_002831.jpg
[ 0 13 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_002831.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_002833.jpg
[ 0 12]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_002833.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_002841.jpg
[ 0  6  7 15 19 20]
Segmentation Mask Saved at: /home/dongw

[ 0  7  9 15 18 20]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_003079.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_003085.jpg
[ 0 13 15]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_003085.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_003089.jpg
[ 0  5  6  7 14 15 19]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_003089.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_003097.jpg
[ 0  9 12 15 18]
Segmentation Mask Saved at: /home/dongwonshin/Desktop/pytorch-semseg/predict_results/fcn16s_pascal_1_99/2011_003097.png
Read Input Image from : /home/dongwonshin/Desktop/Datasets/benchmark_RELEASE/dataset/img/2011_003103.jpg
[ 0  9 15 16 18]
Segmentation